name: Test, Build & Publish

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/README.md"
      - "**/.github"
      - "**/.vscode"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  Test:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v2.5.0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "go.mod"

      - name: Cache golangci-lint
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: cache-golangci-lint
        with:
          path: /usr/local/bin/golangci-lint
          key: golangci-lint-${{ env.GOLANGCI_LINT_VERSION }}-${{ runner.os }}

      - name: Setup golangci-lint
        if: steps.cache-golangci-lint.outputs.cache-hit != 'true'
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b /usr/local/bin ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Run pre-commit hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          distribution: goreleaser
          version: latest
          args: "build --snapshot --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
